[PHP]
expose_php = Off
display_errors = Off
display_startup_errors = Off
log_errors = On
error_log = /proc/self/fd/2
html_errors = Off

memory_limit = 512M
max_execution_time = 120
max_input_time = 120
max_input_vars = 10000
post_max_size = 110M
upload_max_filesize = 100M
file_uploads = On

cgi.fix_pathinfo = 0
variables_order = "EGPCS"

[Session]
session.use_strict_mode = 1
session.use_only_cookies = 1
session.cookie_secure = 1
session.cookie_httponly = 1
session.cookie_samesite = Lax

[opcache]
opcache.enable = 1
opcache.enable_cli = 0
opcache.memory_consumption = 192
opcache.interned_strings_buffer = 16
opcache.max_accelerated_files = 20000
opcache.validate_timestamps = 0
opcache.revalidate_freq = 0
